//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ArrowSchema : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ArrowSchema(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ArrowSchema obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ArrowSchema obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ArrowSchema() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kuzunetPINVOKE.delete_ArrowSchema(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string format {
    set {
      kuzunetPINVOKE.ArrowSchema_format_set(swigCPtr, value);
    } 
    get {
      string ret = kuzunetPINVOKE.ArrowSchema_format_get(swigCPtr);
      return ret;
    } 
  }

  public string name {
    set {
      kuzunetPINVOKE.ArrowSchema_name_set(swigCPtr, value);
    } 
    get {
      string ret = kuzunetPINVOKE.ArrowSchema_name_get(swigCPtr);
      return ret;
    } 
  }

  public string metadata {
    set {
      kuzunetPINVOKE.ArrowSchema_metadata_set(swigCPtr, value);
    } 
    get {
      string ret = kuzunetPINVOKE.ArrowSchema_metadata_get(swigCPtr);
      return ret;
    } 
  }

  public long flags {
    set {
      kuzunetPINVOKE.ArrowSchema_flags_set(swigCPtr, value);
    } 
    get {
      long ret = kuzunetPINVOKE.ArrowSchema_flags_get(swigCPtr);
      return ret;
    } 
  }

  public long n_children {
    set {
      kuzunetPINVOKE.ArrowSchema_n_children_set(swigCPtr, value);
    } 
    get {
      long ret = kuzunetPINVOKE.ArrowSchema_n_children_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_p_ArrowSchema children {
    set {
      kuzunetPINVOKE.ArrowSchema_children_set(swigCPtr, SWIGTYPE_p_p_ArrowSchema.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = kuzunetPINVOKE.ArrowSchema_children_get(swigCPtr);
      SWIGTYPE_p_p_ArrowSchema ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_ArrowSchema(cPtr, false);
      return ret;
    } 
  }

  public ArrowSchema dictionary {
    set {
      kuzunetPINVOKE.ArrowSchema_dictionary_set(swigCPtr, ArrowSchema.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = kuzunetPINVOKE.ArrowSchema_dictionary_get(swigCPtr);
      ArrowSchema ret = (cPtr == global::System.IntPtr.Zero) ? null : new ArrowSchema(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_f_p_ArrowSchema__void release {
    set {
      kuzunetPINVOKE.ArrowSchema_release_set(swigCPtr, SWIGTYPE_p_f_p_ArrowSchema__void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = kuzunetPINVOKE.ArrowSchema_release_get(swigCPtr);
      SWIGTYPE_p_f_p_ArrowSchema__void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_f_p_ArrowSchema__void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void private_data {
    set {
      kuzunetPINVOKE.ArrowSchema_private_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = kuzunetPINVOKE.ArrowSchema_private_data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public ArrowSchema() : this(kuzunetPINVOKE.new_ArrowSchema(), true) {
  }

}
