//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum kuzu_data_type_id {
  KUZU_ANY = 0,
  KUZU_NODE = 10,
  KUZU_REL = 11,
  KUZU_RECURSIVE_REL = 12,
  KUZU_SERIAL = 13,
  KUZU_BOOL = 22,
  KUZU_INT64 = 23,
  KUZU_INT32 = 24,
  KUZU_INT16 = 25,
  KUZU_INT8 = 26,
  KUZU_UINT64 = 27,
  KUZU_UINT32 = 28,
  KUZU_UINT16 = 29,
  KUZU_UINT8 = 30,
  KUZU_INT128 = 31,
  KUZU_DOUBLE = 32,
  KUZU_FLOAT = 33,
  KUZU_DATE = 34,
  KUZU_TIMESTAMP = 35,
  KUZU_TIMESTAMP_SEC = 36,
  KUZU_TIMESTAMP_MS = 37,
  KUZU_TIMESTAMP_NS = 38,
  KUZU_TIMESTAMP_TZ = 39,
  KUZU_INTERVAL = 40,
  KUZU_FIXED_LIST = 41,
  KUZU_INTERNAL_ID = 42,
  KUZU_STRING = 50,
  KUZU_BLOB = 51,
  KUZU_VAR_LIST = 52,
  KUZU_STRUCT = 53,
  KUZU_MAP = 54,
  KUZU_UNION = 55,
  KUZU_RDF_VARIANT = 56,
  KUZU_POINTER = 57,
  KUZU_UUID = 58
}
