//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace KuzuDB {

public class kuzu_internal_id_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal kuzu_internal_id_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(kuzu_internal_id_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(kuzu_internal_id_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~kuzu_internal_id_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          KuzuDBPINVOKE.delete_kuzu_internal_id_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_uint64_t table_id {
    set {
      KuzuDBPINVOKE.kuzu_internal_id_t_table_id_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (KuzuDBPINVOKE.SWIGPendingException.Pending) throw KuzuDBPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(KuzuDBPINVOKE.kuzu_internal_id_t_table_id_get(swigCPtr), true);
      if (KuzuDBPINVOKE.SWIGPendingException.Pending) throw KuzuDBPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64_t offset {
    set {
      KuzuDBPINVOKE.kuzu_internal_id_t_offset_set(swigCPtr, SWIGTYPE_p_uint64_t.getCPtr(value));
      if (KuzuDBPINVOKE.SWIGPendingException.Pending) throw KuzuDBPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64_t ret = new SWIGTYPE_p_uint64_t(KuzuDBPINVOKE.kuzu_internal_id_t_offset_get(swigCPtr), true);
      if (KuzuDBPINVOKE.SWIGPendingException.Pending) throw KuzuDBPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public kuzu_internal_id_t() : this(KuzuDBPINVOKE.new_kuzu_internal_id_t(), true) {
  }

}

}
