//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class kuzu_system_config : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal kuzu_system_config(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(kuzu_system_config obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(kuzu_system_config obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~kuzu_system_config() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          kuzunetPINVOKE.delete_kuzu_system_config(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ulong buffer_pool_size {
    set {
      kuzunetPINVOKE.kuzu_system_config_buffer_pool_size_set(swigCPtr, value);
    } 
    get {
      ulong ret = kuzunetPINVOKE.kuzu_system_config_buffer_pool_size_get(swigCPtr);
      return ret;
    } 
  }

  public ulong max_num_threads {
    set {
      kuzunetPINVOKE.kuzu_system_config_max_num_threads_set(swigCPtr, value);
    } 
    get {
      ulong ret = kuzunetPINVOKE.kuzu_system_config_max_num_threads_get(swigCPtr);
      return ret;
    } 
  }

  public bool enable_compression {
    set {
      kuzunetPINVOKE.kuzu_system_config_enable_compression_set(swigCPtr, value);
    } 
    get {
      bool ret = kuzunetPINVOKE.kuzu_system_config_enable_compression_get(swigCPtr);
      return ret;
    } 
  }

  public bool read_only {
    set {
      kuzunetPINVOKE.kuzu_system_config_read_only_set(swigCPtr, value);
    } 
    get {
      bool ret = kuzunetPINVOKE.kuzu_system_config_read_only_get(swigCPtr);
      return ret;
    } 
  }

  public ulong max_db_size {
    set {
      kuzunetPINVOKE.kuzu_system_config_max_db_size_set(swigCPtr, value);
    } 
    get {
      ulong ret = kuzunetPINVOKE.kuzu_system_config_max_db_size_get(swigCPtr);
      return ret;
    } 
  }

  public kuzu_system_config() : this(kuzunetPINVOKE.new_kuzu_system_config(), true) {
  }

}
