//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace KuzuDB {

public enum kuzu_data_type_id {
  KUZU_ANY = 0,
  KUZU_NODE = 10,
  KUZU_REL = 11,
  KUZU_BOOL = 22,
  KUZU_INT64 = 23,
  KUZU_INT32 = 24,
  KUZU_INT16 = 25,
  KUZU_DOUBLE = 26,
  KUZU_FLOAT = 27,
  KUZU_DATE = 28,
  KUZU_TIMESTAMP = 29,
  KUZU_INTERVAL = 30,
  KUZU_FIXED_LIST = 31,
  KUZU_INTERNAL_ID = 40,
  KUZU_STRING = 50,
  KUZU_VAR_LIST = 52,
  KUZU_STRUCT = 53
}

}
